# frozen_string_literal: true

source 'https://rubygems.org'
ruby '~> 3.0'

gem 'tk'

group :development, :test do
  gem 'rspec', '~> 3.0'
  gem 'simplecov', require: false
  gem 'rubocop', require: false
end
