# frozen_string_literal: true

source 'https://rubygems.org'

gem 'tk'

group :test do
  gem 'rspec'
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'rubocop', '~> 1.0', require: false
  gem 'rubocop-rspec', require: false
end
